# Generated by Django 4.2.9 on 2024-03-10 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notice', models.TextField(default='', null=True)),
                ('content', models.TextField(default='', null=True)),
                ('medium', models.CharField(choices=[('OVA', 'OVA'), ('TVA', 'TVA'), ('극장판', '극장판'), ('기타', '기타')], max_length=10)),
                ('content_rating', models.CharField(choices=[('15세 이용가', '15세 이용가'), ('성인 이용가', '성인 이용가'), ('전체 이용가', '전체 이용가'), ('12세 이용가', '12세 이용가'), ('7세 이용가', '7세 이용가')], max_length=10)),
                ('is_ending', models.BooleanField(default=False)),
                ('production', models.CharField(choices=[('8bit', '8bit'), ('A-1Pictures', 'A-1Pictures'), ('BN Pictures', 'BN Pictures'), ('C2C', 'C2C'), ('CloverWorks', 'CloverWorks'), ('J.C.Staff', 'J.C.Staff'), ('KinemaCitrus', 'KinemaCitrus'), ('MAPPA', 'MAPPA'), ('Nexus', 'Nexus'), ('P.A.Works', 'P.A.Works'), ('TMS 엔터테인먼트', 'TMS 엔터테인먼트'), ('TVTokyo', 'TVTokyo'), ('WIT STUDIO', 'WIT STUDIO'), ('WitStudio', 'WitStudio'), ('Zero-G', 'Zero-G'), ('데이비드 프로덕션', '데이비드 프로덕션'), ('동화공방', '동화공방'), ('라르케', '라르케'), ('라이덴필름', '라이덴필름'), ('매드하우스', '매드하우스'), ('본즈', '본즈'), ('뿡빵뀨', '뿡빵뀨'), ('사테라이트', '사테라이트'), ('샤프트', '샤프트'), ('선라이즈', '선라이즈'), ('스튜디오 딘', '스튜디오 딘'), ('스튜디오 바인드', '스튜디오 바인드'), ('스튜디오 피에로', '스튜디오 피에로'), ('신에이 동화', '신에이 동화'), ('실버 링크', '실버 링크'), ('유포테이블', '유포테이블'), ('쿄토 애니메이션', '쿄토 애니메이션'), ('쿄토애니메이션', '쿄토애니메이션'), ('토에이 애니메이션', '토에이 애니메이션'), ('트리거', '트리거'), ('폴리곤 픽쳐스', '폴리곤 픽쳐스'), ('프로덕션 I.G', '프로덕션 I.G'), ('화이트폭스', '화이트폭스')], max_length=50, null=True)),
                ('is_dubbed', models.BooleanField(default=False)),
                ('is_uncensored', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='animations.series')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('가족', '가족'), ('감동', '감동'), ('게임', '게임'), ('동물', '동물'), ('동양풍', '동양풍'), ('두뇌싸움', '두뇌싸움'), ('로봇', '로봇'), ('루프물', '루프물'), ('마법소녀', '마법소녀'), ('먼치킨', '먼치킨'), ('무거움', '무거움'), ('배틀', '배틀'), ('뱀파이어', '뱀파이어'), ('복수', '복수'), ('삼각관계', '삼각관계'), ('서양풍', '서양풍'), ('선생님', '선생님'), ('성별전환', '성별전환'), ('성장', '성장'), ('슬픔', '슬픔'), ('시간여행', '시간여행'), ('역하렘', '역하렘'), ('연예인', '연예인'), ('열혈', '열혈'), ('오타쿠', '오타쿠'), ('요괴 및 괴물', '요괴 및 괴물'), ('육아', '육아'), ('정치', '정치'), ('좀비', '좀비'), ('주체적 여성', '주체적 여성'), ('짝사랑', '짝사랑'), ('철학', '철학'), ('퇴마', '퇴마'), ('학교', '학교')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='animations.animation')),
            ],
            options={
                'unique_together': {('animation', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('img_url', models.CharField(max_length=1024)),
                ('option_name', models.CharField(choices=[('home_default', 'home_default'), ('home_custom', 'home_custom')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animations.animation')),
            ],
            options={
                'unique_together': {('animation', 'option_name')},
            },
        ),
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrators', to='animations.animation')),
            ],
            options={
                'unique_together': {('animation', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BL', 'BL'), ('GL 백합', 'GL 백합'), ('SF', 'SF'), ('개그', '개그'), ('공포', '공포'), ('드라마', '드라마'), ('로맨스', '로맨스'), ('모험', '모험'), ('무협', '무협'), ('미스터리', '미스터리'), ('범죄', '범죄'), ('성인', '성인'), ('스릴러', '스릴러'), ('스포츠', '스포츠'), ('시대물', '시대물'), ('아동', '아동'), ('아이돌', '아이돌'), ('악역영애', '악역영애'), ('액션', '액션'), ('음식', '음식'), ('음악', '음악'), ('이세계', '이세계'), ('일상', '일상'), ('재난', '재난'), ('추리', '추리'), ('치유', '치유'), ('특촬', '특촬'), ('판타지', '판타지'), ('하렘', '하렘')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='animations.animation')),
            ],
            options={
                'unique_together': {('animation', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='animations.animation')),
            ],
            options={
                'unique_together': {('animation', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='animations.animation')),
            ],
            options={
                'unique_together': {('animation', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Air',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_year_quaters', to='animations.animation')),
            ],
            options={
                'unique_together': {('animation', 'year', 'quarter')},
            },
        ),
    ]
