# Generated by Django 4.2.9 on 2024-02-07 21:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
                ('img', models.ImageField(default='.', max_length=1024, upload_to='')),
                ('published_at', models.DateField()),
                ('is_ending', models.BooleanField(default=False)),
                ('is_dubbed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='animations.animation')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(choices=[('P', 'Prejudice'), ('S', 'Sexual Situation'), ('V', 'Violence'), ('L', 'Language'), ('H', 'Horror'), ('D', 'Substance Abuse'), ('I', 'Imiation Risk')], max_length=30)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='animations.animation')),
            ],
        ),
        migrations.CreateModel(
            name='ContentElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(choices=[('P', 'Prejudice'), ('S', 'Sexual Situation'), ('V', 'Violence'), ('L', 'Language'), ('H', 'Horror'), ('D', 'Substance Abuse'), ('I', 'Imiation Risk')], max_length=5)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_elements', to='animations.animation')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='animations.animation')),
            ],
        ),
        migrations.AddField(
            model_name='animation',
            name='content_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animations.contentrating'),
        ),
        migrations.AddField(
            model_name='animation',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animations.production'),
        ),
    ]
